sudo: required

services:
  - docker

language: go

go:
  - '1.5'

env:
  global:
    - secure: "FCB0vsh91FeQYCDgINuL5Cqz+l9iKhPPhMUNTfYHIQ8MHlPRb2XyLzRrvH8BrN66qZaV0BzBPmC5dxWo7HNi6wIKiLFKJwXEWzfbxaKcULjurm3t+Z3A8EMfIxl0BJmPJi/FKF6o4CWkaAYMiIRM6tXJAjhaqZhW+XGL+/KBfEdJ47jSl2bdOwY8wL5zoSPDWTKO9Qjv9KejtxMS2OA+wn8dlPq8kNLeVIJm+kW5lgCxyNRK3PbD/1oTyc9u25YdkG/KPL+OJyOFkFqooGuumX+jPef3ZlRWjKukaM+ljTHit2lsGFaVnvhcVLt0T068kx/yG4OWEFBVOaHaoVPPco4m0KYF3xPgRpPRb1lrXjv+90SWrUMoyl/bBddq52ux+wESkS1EJLh/M8YtiAxKz/0q/lGB+AP78Cok5wgUqsLHKtGjr2AcqhDwz9A9lZJOSkXYBr4uWDUIPjune6q+K6LIrZrOIYgpAYAszMEBydNFw2WywE19iU1vtsDYZGj5jAzD0uS2LSETfs/rIe3vFK2JBpartveYpiErSzPE1QENgylh1dX6YyQQUn/vmn5Q0YwYAx6gAivUvhaS6UsTjb8+HUv17V/h0ZghCTM2Q+b73tMp2d/g33MLU5MMpAiytcIJkBWaOvXjOwRA/gA5JV8iE6MHpKByDzCT+2B7ayE="
    - secure: "SJdMd+iUPkCOKEFcDuUSIVPjz6ZbPDCI2/WUs7xVQX0sGU6thOLQxMM/mi8++G+d5PFoAkBc9l2dW6Ca2f93c3LFyrHgrJk8CGPyXK+J91Fw7rKXTYdifzzj44sx9V4eg1EP7wly17ueitrVEejhXkw8jhXA1C7zWrs7uLIKfS2MAPTv7SSMKO9prnE7zMRFzIlr3bV0id4fsrcJkyTNQJvqCLJj47bUDlSRXiJPMoM+GV9uCvHprh1cyrg5f8FNug2eN20G7DGli+vELyAFssZvfgb++wSuoEwDcFvb/L5M9Bh6X+UJJfQM8Vt70Tvv6YMgLGLHIpNEGCftQ6Bo3njeJeps8NZb0xBy5meSFop1E6CtW5AJjz0NZMmgW1vxdWSRlubBn/ibV+tQx9ff6jAIpZ7WM6e4TTuGhO66gpfO6GTDt5WlclIU/UDvW3aM9eZVwL6bT0LTzU2AE2thFFQIEOjGOkquWXkDoA30JGWrYlYdUSIISf6SRY/2Va0ZUdK1hjzvEJ014TexCfnHzZkBAXvgGu7X1H6G3fw/U2UiPQ+y73e1KcT5a+vV152jFmkRQOdgSzhiAuzLqPRLTI8jbdq2WJIlCCFCO5+thFGDt0+8PDt7D/jmtSKUZQfyKyDS5ok7TQSpERBDXKREad3e9U0AQuQs6tyiHcZffpM="
    - COMMIT=${TRAVIS_COMMIT::8}

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=nocquidant/hello-trainee
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
